### ISSUE TITLE
Куда закидывать конфиг в впн?

### ISSUE THREAD

**Issue by Ggglolkek4004** [iamkuper/amnezia-discord-config#1]

**Comment by Ggglolkek4004** [comment]
Ото закинул в корень и ничего

**Comment by iamkuper** [comment]
Добавил инструкцию в README.md

**Comment by Ggglolkek4004** [comment]
Я понял, но теперь у меня бесконечное подключение к голосовому каналу

**Comment by Ggglolkek4004** [comment]
Там возможно свои адресса

**Comment by Ggglolkek4004** [comment]
Не удаётся зайти

**Comment by Ggglolkek4004** [comment]
Подключение к RTC и потом не удалось

**Comment by iamkuper** [comment]
Через Amnezia или GoodbuyDPI?
С амнезией должно работать, гудбай не будет работать войс

**Comment by Ggglolkek4004** [comment]
Amnezia

**Comment by Ggglolkek4004** [comment]
![image](https://github.com/user-attachments/assets/5084fb63-9218-4dc4-b141-fb42b0e814d2)
Импорт сделал

**Comment by Ggglolkek4004** [comment]
Не знаю сейчас что-то вообще не заходит

**Comment by Ggglolkek4004** [comment]
Похоже надо ещё домены дискорда накинуть которые люди писали для гудбая в других способах

**Comment by iamkuper** [comment]
попробуй еще а Амнезии изменить голосовые сервера на какие нить европейские

**Comment by iamkuper** [comment]
> Похоже надо ещё домены дискорда накинуть которые люди писали для гудбая в других способах

домены там уже есть) точнее их адреса + адреса войс серверов

**Comment by Ggglolkek4004** [comment]
Я домены добавил и смог на сайт дс зайти

**Comment by iamkuper** [comment]
> Я домены добавил и смог на сайт дс зайти

Добавил еще все адреса из A записей доменов в конфиг
