### ISSUE TITLE
На шаге выбора региона отсутствует tel-aviv

### ISSUE THREAD

**Issue by impaxel** [iamkuper/amnezia-discord-config#10]
Все остальные регионы представлены

![image](https://github.com/user-attachments/assets/49d39451-8ada-4c19-8e5e-0196b943c443)

**Comment by iamkuper** [comment]
> Все остальные регионы представлены
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/49d39451-8ada-4c19-8e5e-0196b943c443)
> 
> 

Видно пропустил) Хотя адреса есть его. Скоро внесу
