### ISSUE TITLE
После импорта списка IP в Amnezia VPN не подключается

### ISSUE THREAD

**Issue by JonasWebeer** [iamkuper/amnezia-discord-config#3]
Был старый список IP и там подключалось. Скачал сейчас новый список - и при нажатии кнопки подключения, ничего не происходит. 
Проблема старого списка что никому не могу файлы отправить никакие. 
Без тунелирования всё работает хорошо.

**Comment by xtclovver** [comment]
@JonasWebeer ты добавил к своему списку или импортировал с заменой старого?

**Comment by Varekee** [comment]
Точно такая же проблема. При импортировании списка IP адресов в Amnezia VPN подключения не происходит.
При очистке списка (импортировании пустого), подключение происходит нормально.

**Comment by Varekee** [comment]
@xtclovver у меня не было списка ранее. Импортировал с заменой старого.

**Comment by iamkuper** [comment]
> Точно такая же проблема. При импортировании списка IP адресов в Amnezia VPN подключения не происходит. При очистке списка (импортировании пустого), подключение происходит нормально.

возможно IP адреса сервера VPN попадает в какую то подсеть дискорда 
1. Добавить исключение для адреса сервера впн
2. Подождать чуть (обновляю списки на более точные)

**Comment by Varekee** [comment]
@iamkuper в Amnezia VPN разве можно добавить два вида фильтров для раздельного туннелирования?
Выбор либо:
1. Адреса из списка не должны открываться
2. Только адреса из списка должны открываться

Задача заставить работать через Amnezia VPN только DIscord.

**Comment by iamkuper** [comment]
> @iamkuper в Amnezia VPN разве можно добавить два вида фильтров для раздельного туннелирования? Выбор либо:
> 
> 1. Адреса из списка не должны открываться
> 2. Только адреса из списка должны открываться
> 
> Задача заставить работать через Amnezia VPN только DIscord.

ну значит 2 вариант) либо ручками найти подсеть в которую попадает VPN сервер и удалить из

**Comment by megarungle** [comment]
Судя по всему, @iamkuper немного не туда вписал адреса при формировании JSON.

Исходя из информации в этом топике https://github.com/amnezia-vpn/amnezia-client/issues/417, при импорте используется только поле "ip".

Заменить `"hostname": "([0-9.]*)",\n    "ip": ""` на `"hostname": "",\n    "ip": "$1"`. Если импортировать список в таком формате, Amnezia начинает сама группировать все адреса по подсетям, из-за чего, к слову, перестаёт фризить.

Тем не менее, даже с этим учетом, подключение не устанавливается.

**Comment by iamkuper** [comment]
> Судя по всему, @iamkuper немного не туда вписал адреса при формировании JSON.
> 
> Исходя из информации в этом топике [amnezia-vpn/amnezia-client#417](https://github.com/amnezia-vpn/amnezia-client/issues/417), при импорте используется только поле "ip".
> 
> Заменить `"hostname": "([0-9.]*)",\n "ip": ""` на `"hostname": "",\n "ip": "$1"`. Если импортировать список в таком формате, Amnezia начинает сама группировать все адреса по подсетям, из-за чего, к слову, перестаёт фризить.
> 
> Тем не менее, даже с этим учетом, подключение не устанавливается.

разницы по идее нет - Amnezia оба поля воспринимает (проверено)
но да исправлю чтоб адреса попадали в список ip а домены в hostname

**Comment by megarungle** [comment]
Если бы адресов было ещё больше, приложение может либо крашнуться, либо встать намертво :)
Да, лучше поправить. Спасибо.

**Comment by megarungle** [comment]
Наблюдение: после импорта списка, удалил адрес 5.200.14.128/2. Подключение устанавливается. На первый взгляд, Дискорд работает, ГС функционирует.

**Comment by megarungle** [comment]
Инструкция, для тех, кто не хочет ждать (работает по крайней мере для меня):
1. Чуть выше я оставил регулярные выражения. В любом текстовом редакторе делаем замену;
2. Импортируем обновленный конфиг;
3. Удаляем из списка запись 5.200.14.128/2.

@JonasWebeer @Varekee

**Comment by iamkuper** [comment]
> Наблюдение: после импорта списка я удалил адрес 5.200.14.128/2. Подключение устанавливается. На первый взгляд, Дискорд работает, ГС функционирует.

Ближе к вечеру проблему пофикшу и залью:

- [x] Получение полного списка адресов методом DNS Resolve
- [x] Конфигуратор
- [x] Формирование на основе адресов списка подсетей (чтоб файл был меньше, для слабых устройств)


![screenshot](https://github.com/user-attachments/assets/1a001dcb-854a-449b-a8db-92663e9e1f25)

**Comment by Varekee** [comment]
@megarungle большое спасибо! После правок перестал фризить клиент Amnezia VPN, подключение успешно, Discord работает.

**Comment by iamkuper** [comment]
@megarungle @Varekee @JonasWebeer 
обновил список адресов
