### ISSUE TITLE
Через какое то время после запуска отключается стим

### ISSUE THREAD

**Issue by X3nard** [iamkuper/amnezia-discord-config#4]
заметил что когда сижу с включенным AmneziaVPN то примерно через минут 20 стим пишет что нет соединения. После того как выключаю и включаю впн стим снова входит в сеть

**Comment by iamkuper** [comment]
Все рекомендуется делать на приватном сервере Amnezia) Паблики тупят жестко

**Comment by hfMoooon** [comment]
"Приватном сервере" - амнезии, запущенной на своём сервере? Если да, у меня свой сервер - проблема со стимом присутсвует. 
Даже если был бы общий сервер, как связан сервер с проблемой со стимом, если трафик до него не идёт через впн? Разве дело не в списке IP, в который случайно попал стим?

**Comment by dmis0k** [comment]
@iamkuper у меня приватный сервер. С данной конфигурацией не работает магазин стима. Сообщества и все остальное в самом стиме работает нормально. Как только отключаю раздельное туннелирование магазин работает без проблем.

**Comment by X3nard** [comment]
я попытался добавить стим в черный список и после этого он заработал

**Comment by X3nard** [comment]
я добавил в черный список эти домены 
steam-content-dnld-1.qwilted-cds.cqloud.com
steam-software.dlt.qwilted-cds.cqloud.com
steamusercontent.com
steamstatic.com
steam-chat.com
steamserver.net
steampowered.com
steamcommunity.com
store.steampowered.com
надеюсь кому поможет

**Comment by xtclovver** [comment]
@X3nard Спасибо большое!

**Comment by hfMoooon** [comment]
@X3nard В амнезии можно использовать одновременно и белый список, и чёрный?

**Comment by iamkuper** [comment]
> steam-content-dnld-1.qwilted-cds.cqloud.com
> steam-software.dlt.qwilted-cds.cqloud.com
> steamusercontent.com
> steamstatic.com
> steam-chat.com
> steamserver.net
> steampowered.com
> steamcommunity.com
> store.steampowered.com

проверю пересечения) чуть позже обновлю списки - щас резолвинг идет войс адресов по регионам

**Comment by iamkuper** [comment]
> "Приватном сервере" - амнезии, запущенной на своём сервере? Если да, у меня свой сервер - проблема со стимом присутсвует. Даже если был бы общий сервер, как связан сервер с проблемой со стимом, если трафик до него не идёт через впн? Разве дело не в списке IP, в который случайно попал стим?

возможно да попали адреса - щас по другому получаю их (резолвинг по доменам) чуть позже обновлю репу
+ сведу списки адресов в подсети

**Comment by X3nard** [comment]
@hfMoooon да работает

**Comment by dmis0k** [comment]
> @hfMoooon да работает

у меня не работает так.

**Comment by iamkuper** [comment]
@hfMoooon @dmis0k @X3nard @xtclovver обновил репозиторий) проверить бы работает стим или нет
