### ISSUE TITLE
all.subnets.json поломан

### ISSUE THREAD

**Issue by Shamilik** [iamkuper/amnezia-discord-config#7]
Кажется, что hostname & ip перепутаны местами. Amnezia принимает конфиг с ip в поле hostname.

**Comment by iamkuper** [comment]
Амнезия не принимает subnets просто))) пустота после импорта - используйте IP
разницы там нет где IP и где по адреса по полям

> Кажется, что hostname & ip перепутаны местами. Amnezia принимает конфиг с ip в поле hostname.

**Comment by d-a-bunin** [comment]
Подтверждаю проблему. У меня получилось пропихнуть файл с `all.ips.json` только после того, как я скриптом поменял значения полей `ip` и `hostname`.
