### ISSUE TITLE
Скрипт создания конфига добавляет все адреса независимо от выбора пользователя

### ISSUE THREAD

**Issue by impaxel** [iamkuper/amnezia-discord-config#9]
Для создания конфига выбрал только ru сервера, но в готовом файле все равно содержались записи всех серверов + основные, выбор пользователя игнорируется.

![image](https://github.com/user-attachments/assets/c4996e02-7392-479e-9156-528475dd44b1)

**Comment by iamkuper** [comment]
> Для создания конфига выбрал только ru сервера, но в готовом файле все равно содержались записи всех серверов + основные, выбор пользователя игнорируется.
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/c4996e02-7392-479e-9156-528475dd44b1)
> 
> 

Общие адреса всеравно добавляются. Вот Атланты быть не должно - проверю

**Comment by kenclaron** [comment]
Возможно, https://github.com/iamkuper/amnezia-discord-config/pull/12 решит проблему, т.к. в скрипте читался файл со всеми, а выбранные регионы никак не влияли на дальнейшее формирование конфига
